version: "3.9"
services:
  discord:
    image: kevincmanning/discord-bot
    secrets:
      - source: discord_key
        target: spring.discord.key
      - source: teemo_api_key
        target: spring.teemo.api.key

secrets:
  discord_key:
    external: true
  teemo_api_key:
    external: true