# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Maven Cache
      uses: skjolber/maven-cache-github-action@v1.1
      with:
        step: save

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      
    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.9.0
      with:
        context: .
        push: true
        file: ./discord-bot/Dockerfile
        tags: kevincmanning/discord-bot:latest
    
    - name: Docker remote pull
      uses: TapTap21/docker-remote-deployment-action@v1.0
      with:
        remote_docker_host: root@rsc.world
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        docker_login_password: ${{ secrets.DOCKERHUB_TOKEN }}
        docker_login_user: ${{ secrets.DOCKERHUB_USERNAME }}
        args: pull
            
    - name: Docker remote down
      uses: TapTap21/docker-remote-deployment-action@v1.0
      with:
        remote_docker_host: root@rsc.world
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        docker_login_password: ${{ secrets.DOCKERHUB_TOKEN }}
        docker_login_user: ${{ secrets.DOCKERHUB_USERNAME }}
        args: down
            
    - name: Docker remote up
      uses: TapTap21/docker-remote-deployment-action@v1.0
      with:
        remote_docker_host: root@rsc.world
        ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
        ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
        stack_file_name: docker-compose.yml
        docker_login_password: ${{ secrets.DOCKERHUB_TOKEN }}
        docker_login_user: ${{ secrets.DOCKERHUB_USERNAME }}
        args: -p myapp up -d
